/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from "ethereum-types";

import * as OptionToken from "../generated-artifacts/OptionToken.json";
import * as OptionTokenTest from "../generated-artifacts/OptionTokenTest.json";
export const artifacts = {
  OptionToken: OptionToken as ContractArtifact,
  OptionTokenTest: OptionTokenTest as ContractArtifact
};
